config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home',to: 'pages#home'
  get '/signup',to: 'chefs#new'
  resources :recipes
  resources :chefs
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :ingredients,except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,presence: true
  validates :description,presence: true
  belongs_to :user
end

app/models/chef.rb
class Chef<ApplicationRecord
  has_secure_password
  validates :name,presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence: true,length: {maximum: 255},format: {with: VALID_EMAIL_REGEX}
  has_many :recipes,dependent: :destroy
  validates :password,presence: true,length: {minimum: 5}
  has_many :comments,dependent: :destroy
end

app/models/comment.rb
class Comment<ApplicationRecord
  validates :description,presence: true,length: {minimum: 4,maximum: 140}
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id,presence: true
  default_scope -> {order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient<ApplicationRecord
    validates :name, presence: true,length: {minimum: 3,maximum: 30}
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipes,through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name,presence: true,length: {maximum: 30}
  validates :description,presence: true,length: {maximum: 255}
  belongs_to :chef
  validates :chef_id,presence: true
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments,dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient<ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User<ApplicationRecord
  validates :name,presence: true
  validates :email,presence: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # code to enable methods to be usable in views
  helper_method :current_chef,:logged_in?
  def current_chef
    # if current_chef is already explored no need to hit database
    # just use ||= operator
   @current_chef ||= Chef.find(session[:chef_id]) if session[:chef_id]
    # this line is going to be returned
  end

  def logged_in?
    # !! turns any expression into true or false
    !!current_chef
  end

  def require_user
    if !logged_in?
      flash[:danger]="No user is currently logged in"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef,only: [:edit, :update, :show, :destory]
  before_action :require_same_user,only: [:edit,:destroy,:update]
  before_action :require_admin,only: [:destroy]
  def index
    @chef=Chef.all
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef=Chef.new(chef_params)
    if @chef.save
        session[:chef_id]=@chef.id
        flash[:success]="Welcome #{@chef.name} to MyRecipe App"
        redirect_to  chef_path(@chef)
    else
        render 'new'
    end
  end

  def show
    @chef_recipe=@chef.recipes.paginate(page: params[:page],per_page: 5)
  end

  def destroy
    @chef=Chef.find(params[:id])
    if !@chef.admin?
      @chef.destroy
      flash[:danger]="Chef and all associated recipes have been deleted"
      redirect_to '/chefs',status: :see_other
    end
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:notice]="Chef was Updated Successfully"
      redirect_to  chef_path(@chef)
    else
      render 'edit'
    end
  end

  private

  def chef_params
      params.require(:chef).permit(:name,:email,:password,:password_confirmation)
  end

  def set_chef
    @chef=Chef.find(params[:id])
  end
  def require_same_user
    if current_chef!=@chef and !current_chef.admin?
      flash[:danger]="You are only allowed to delete your own account"
      redirect_to chefs_path
    end
  end

  def require_admin
    if logged_in? && !current_chef.admin?
      flash[:danger]="Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredients,only:   [:edit,:show,:update]
  before_action :require_admin,except: [:show,:index]
  def index
    @ingredient=Ingredient.paginate(page: params[:page],per_page: 5)
  end

  def new
    @ingredient=Ingredient.new
  end

  def create
    @ingredient=Ingredient.new(set_ingredients_params)
    if @ingredient.save
      flash[:success]="Ingredient has been succssfully Saved"
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def edit
  end

  def show
    @ingredient_recipes=@ingredient.recipes.paginate(page: params[:page],per_page: 5)
  end

  def update
    if @ingredient.update(set_ingredients_params)
      flash[:notice]="Ingredient was Updated Successfully"
      redirect_to  ingredient_path(@ingredient)
    else
      render 'edit'
    end
  end

  private

  def set_ingredients_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredients
    @ingredient=Ingredient.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in?  and !current_chef.admin?)
      flash[:danger]="Only admin users can perform that action"
      redirect_to ingredients_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe,only: [:edit, :update, :show, :destory]
  before_action :require_user,except: [:index,:show]
  before_action :require_same_user,only: [:edit,:destroy,:update]
  def index
    @recipes=Recipe.paginate(page: params[:page],per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe=Recipe.new(recipe_params)
    @recipe.chef=current_chef
    if @recipe.save
        flash[:notice]="Recipe was created Successfully"
        redirect_to  recipe_path(@recipe)
    else
        render 'new'
    end
  end

  def show
    @comments=@recipe.comments.paginate(page: params[:page],per_page: 5)
  end

  def destroy
    @recipe.destroy
     redirect_to '/recipes',status: :see_other
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice]="Recipe was Updated Successfully"
      redirect_to  recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  private

  def recipe_params
      params.require(:recipe).permit(:name,:description,ingredient_ids: [])
  end

  def set_recipe
    @recipe=Recipe.find(params[:id])
  end

  def require_same_user
    if current_chef!=@recipe.chef and !current_chef.admin?
      flash[:danger]="You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    chef=Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id]=chef.id
      flash[:success]="You have successfully logged in"
      redirect_to chef_path(chef)
    else
      flash.now[:danger]="There was something wrong with your login info"
      render 'new'
    end
  end
  def destroy
    session[:chef_id]=nil
    flash[:success]="You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={})
    gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
    size=options[:size||80]
    gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.name,class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/chefs/_form.html.erb
<div class="row">
    <div class="col-md-12">
        <%= form_for(@chef,:html=>{class: "form-horizontal",role:"form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :name,"Choose Chefname" %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name,class: "form-control",placeholder: "Enter your name",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :email,"Email" %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :email,class: "form-control",placeholder: "Enter your email",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :password %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :password,type: "password",class: "form-control",placeholder: "Choose a password",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :password_confirmation,"Confirm Password" %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :password_confirmation,type: "password",class: "form-control",placeholder: "Confirm password",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit(@chef.new_record? ? "Create Account" : "Update Account", class: "btn btn-primary btn-lg btn-xlarge") %>
                </div>
            </div>
        <% end %>
        <div class="center colormatch">
            Already have an Account? [ <%= link_to "Log in",login_path %> ]
        </div>
    </div>
</div>

app/views/chefs/edit.html.erb
<%= render "shared/page_title",title: "Edit your profile" %>
<hr/>
<%= render "shared/errors", obj:@chef%>
<%= render "form" %>

app/views/chefs/index.html.erb
<%= render "shared/page_title",title:"Showing all Chefs" %>
<div align="center">
    <% @chef.each do |chef|%>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4" >
                    <li ><%= link_to gravatar_for(chef), chef_path(chef) %></li>
                    <li class="chef-title">
                        <%= link_to chef.name.capitalize,chef_path(chef) %>
                        <li><small><%= pluralize(chef.recipes.count,"recipe") if chef.recipes %></small></small></li>
                        <% if logged_in? && current_chef.admin? && !chef.admin? %>
                            <li><%= button_to "Delete this chef",chef_path(chef),method: :delete,data:{turbo_confirm: "Are you sure you want to delete the chef and all associated recipes?"} ,class:"btn-danger"%></li>
                        <% end %>
                    </li>
                </div>
            </div>

        </ul>
    <% end; %>
</div>

app/views/chefs/new.html.erb
<%= render "shared/page_title",title: "Sign up for the Appluication" %>
<hr/>
<%= render "shared/errors", obj:@chef%>
<%= render "form" %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title',title:"Chef #{@chef.name}'s profile" %>
<div class="row">
    <div class="col-md-4 col-md-offset-4 center">
        <%= gravatar_for @chef,size: 150%>
    </div>
</div>
<% if @chef.recipes.count != 0 %>
<h4 align="center"><%= @chef.name%>'s recipes</h4>
<div align="center">
    <%= will_paginate @chef_recipe%>
<%= render 'recipes/recipe',obj:@chef.recipes %>
    <%= will_paginate @chef_recipe%>
</div>
<% else %>
<h4 align="center">No Recipes Yet</h4>
<% end %>

app/views/ingredients/_form.html.erb
<%= render "shared/errors",obj: @ingredient  %>
<div class="row">
    <div class="col-md-12">
        <%= form_for(@ingredient,:html=>{class: "form-horizontal",role:"form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name,class: "form-control",placeholder: "Enter Ingredient",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
                </div>
            </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Cancel Request and return to recipes listing",recipes_path %>]
        </div>
    </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge">
<%= link_to ingredient.name,ingredient_path(ingredient) %>&nbsp
</span>

app/views/ingredients/edit.html.erb
<%= render "shared/page_title", title:"Edit the Ingredient" %>

<%= render "form" %>

app/views/ingredients/index.html.erb
<%= render "shared/page_title",title:"Available Ingredients" %>
<div align="center">
    <% @ingredient.each do |ing|%>
        <ul class="listing">
            <div class="row">
                <div class="well col-md-4 col-md-offset-4" >
                    <li class="chef-title">
                        <%= link_to ing.name.capitalize,ingredient_path(ing) %>
                        <li><small><%= pluralize(ing.recipes.count,"recipe") if ing.recipes %></small></small></li>
                        <% if logged_in? && current_chef.admin?  %>
                            <li><%= link_to "Edit this Ingredient",edit_ingredient_path(ing) %></li>
                        <% end %>
                    </li>
                </div>
            </div>

        </ul>
    <% end; %>
</div>

app/views/ingredients/new.html.erb
<%= render "shared/page_title", title:"Add new Ingredient" %>

<%= render "form" %>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title',title:" #{@ingredient.name}" %>
<% if @ingredient.recipes.count != 0 %>
<h4 align="center">Recipes Containing <%= @ingredient.name%></h4>
<div align="center">
    <%= will_paginate @ingredient_recipes%>
<%= render 'recipes/recipe',obj:@ingredient_recipes %>
    <%= will_paginate @ingredient_recipes%>
</div>
<% else %>
<h4 align="center">No Recipes Yet</h4>
<% end %>

app/views/recipes/_forms.html.erb
<%= render "shared/errors",obj: @recipe  %>
<div class="row">
    <div class="col-md-12">
        <%= form_for(@recipe,:html=>{class: "form-horizontal",role:"form"}) do |f| %>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :name %>
                </div>
                <div class="col-md-8">
                    <%= f.text_field :name,class: "form-control",placeholder: "Name of Recipe",autofocus:true %>
                </div>
            </div>
            <div class="form-group">
                <div class="control-label col-md-2">
                    <%= f.label :description %>
                </div>
                <div class="col-md-8">
                    <%= f.text_area :description,rows:10,class: "form-control",placeholder: "Add Description" %>
                </div>
            </div>
            <div class="form-group" >
                <div class="row center" >
                <div class="col-offset-2 col-md-8">
                    <%= f.collection_check_boxes :ingredient_ids, Ingredient.all,:id,:name do |cb|%>
                        <% cb.label(check: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox")+cb.text } %>
                    <% end %>
                </div>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
                </div>
            </div>
        <% end %>
        <div class="col-md-4 col-md-offset-4 colormatch">
            [<%= link_to "Cancel Request and return to recipes listing",recipes_path %>]
        </div>
    </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
    <div class="row" >
        <div class="col-md-2" >
            <section class="chef_info center" >
                <%= gravatar_for(recipe.chef,size:120)%>
            </section>
        </div>
        <div class="col-md-8 well" >
            <h4><%= link_to recipe.name,recipe_path(recipe) %></h4>
            <p><%= truncate(recipe.description,length: 150) %></p>

            <% if recipe.ingredients.any? %>
                <p>Ingredients: <%= render recipe.ingredients %> </p>
            <% end %>

            <p>
                <span class="quiet" > <small>Created <%= time_ago_in_words(recipe.created_at) %> ago, by <%= recipe.chef.name%></small> </span>
            </p>

            <% if logged_in? && (current_chef ==recipe.chef || current_chef.admin?) %>
                <div class="recipe-actions">
                    <%= link_to "Edit this recipe",edit_recipe_path(recipe),class: "btn btn-xs btn-warning" %>
                    <%= button_to "Delete this recipe",recipe_path(recipe),class: "btn btn-xs btn-danger",method: :delete,data: {turbo_confirm: "Are you sure?"}%>
                </div>
            <% end %>
        </div>
    </div>
<% end %>

app/views/recipes/_recipeform.html.erb
<% if @recipe.errors.any?%>
	<h3>
		Following are the error that are occuring due to Incorrect Params
	</h3>

	<ul>
		<% @recipe.errors.full_messages.each do |msg|%>
			<li><%=msg%></li>
		<%end%>
  </ul>
<%end%>
<%= form_for @recipe do |f| %>
    <p>
        <%= f.label :name, "Name" %><br>
        <%= f.text_field :name %>
    </p>

    <p>
        <%= f.label :description, "Description" %> <br>
        <%= f.text_area  :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<%end%>

app/views/recipes/edit.html.erb
<%= render "shared/page_title",title: "Edit the Recipe" %>
<%= render "forms" %>

app/views/recipes/index.html.erb
<%= render "shared/page_title",  title: "List of All Recipes" %>
<div align="center">
    <%= will_paginate %>
</div>
<%= render "recipe",obj: @recipes %>
<div align="center">
    <%= will_paginate %>
</div>

app/views/recipes/new.html.erb
<%= render "shared/page_title",title: "create a new recipe" %>
<%= render "forms"%>

app/views/recipes/show.html.erb
<%= render "shared/page_title",  title: "Recipe Name: "+@recipe.name %>
<div class="well col-md-8 col-md-offset-2" >
    <h4 class="center description" ><strong>Steps: </strong></h4>
    <hr />
    <div align="center" >
        <%= simple_format(@recipe.description) %>
        <hr />
        <% if @recipe.ingredients.any? %>
            <p>Ingredient: <%= render @recipe.ingredients %></p>
        <% end %>
        <div class ="pull-right">
            <p class="center">
                <em>Created by:</em>
            </p>
            <p>
                <%= link_to gravatar_for(@recipe.chef),recipe_path%>
            </p>
            <p class="center" >
                <small><%= @recipe.chef.name.capitalize%> </small>
                <div class="pull-right"><%= time_ago_in_words(@recipe.created_at)%> ago</div>
            </p>
        </div>
    </div>
    <div class="recipe-actions">
        <% if logged_in? && (current_chef ==@recipe.chef || current_chef.admin?) %>
            <%= link_to "Edit this recipe",edit_recipe_path(@recipe),class: "btn btn-xs btn-warning" %>
            <%= button_to "Delete this recipe",recipe_path(@recipe),class: "btn btn-xs btn-danger",method: :delete,data: {turbo_confirm: "Are you sure?"}%>
        <% end %>
        <%= link_to "Return this recipe Listing",recipes_path,class: "btn btn-xs btn-primary" %>
    </div>
</div>

<% if @recipe.comments != 0 %>
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <h3>Prior Comments: </h3>
            <div id="messages">
                <%= render  partial: "comments/comments", object: @comments %>
            </div>
        </div>
    </div>
<% else %>
    <div class ="row" >
        <div class="col-md-8 col-md-offset-2">
            <h3>No Comments Yet!</h3>
        </div>
    </div>

<% end %>