config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "pages#home"
  get 'pages/home',to: 'pages#home'
  get '/signup',to: 'chefs#new'
  resources :recipes
  resources :chefs
  # Defines the root path route ("/")
  # root "articles#index"
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'

  resources :ingredients,except: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title,presence: true
  validates :description,presence: true
  belongs_to :user
end

app/models/chef.rb
class Chef<ApplicationRecord
  has_secure_password
  validates :name,presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,presence: true,length: {maximum: 255},format: {with: VALID_EMAIL_REGEX}
  has_many :recipes,dependent: :destroy
  validates :password,presence: true,length: {minimum: 5}
  has_many :comments,dependent: :destroy
end

app/models/comment.rb
class Comment<ApplicationRecord
  validates :description,presence: true,length: {minimum: 4,maximum: 140}
  belongs_to :chef
  belongs_to :recipe
  validates :chef_id, presence: true
  validates :recipe_id,presence: true
  default_scope -> {order(updated_at: :desc)}
end

app/models/ingredient.rb
class Ingredient<ApplicationRecord
    validates :name, presence: true,length: {minimum: 3,maximum: 30}
    validates_uniqueness_of :name
    has_many :recipe_ingredients
    has_many :recipes,through: :recipe_ingredients
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :name,presence: true,length: {maximum: 30}
  validates :description,presence: true,length: {maximum: 255}
  belongs_to :chef
  validates :chef_id,presence: true
  has_many :recipe_ingredients
  has_many :ingredients, through: :recipe_ingredients
  has_many :comments,dependent: :destroy
end

app/models/recipe_ingredient.rb
class RecipeIngredient<ApplicationRecord
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/user.rb
class User<ApplicationRecord
  validates :name,presence: true
  validates :email,presence: true
  has_many :articles
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef,only: [:edit, :update, :show, :destory]
  before_action :require_same_user,only: [:edit,:destroy,:update]
  before_action :require_admin,only: [:destroy]
  def index
    @chef=Chef.all
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef=Chef.new(chef_params)
    if @chef.save
        session[:chef_id]=@chef.id
        flash[:success]="Welcome #{@chef.name} to MyRecipe App"
        redirect_to  chef_path(@chef)
    else
        render 'new'
    end
  end

  def show
    @chef_recipe=@chef.recipes.paginate(page: params[:page],per_page: 5)
  end

  def destroy
    @chef=Chef.find(params[:id])
    if !@chef.admin?
      @chef.destroy
      flash[:danger]="Chef and all associated recipes have been deleted"
      redirect_to '/chefs',status: :see_other
    end
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:notice]="Chef was Updated Successfully"
      redirect_to  chef_path(@chef)
    else
      render 'edit'
    end
  end

  private

  def chef_params
      params.require(:chef).permit(:name,:email,:password,:password_confirmation)
  end

  def set_chef
    @chef=Chef.find(params[:id])
  end
  def require_same_user
    if current_chef!=@chef and !current_chef.admin?
      flash[:danger]="You are only allowed to delete your own account"
      redirect_to chefs_path
    end
  end

  def require_admin
    if logged_in? && !current_chef.admin?
      flash[:danger]="Only admin users can perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe,only: [:edit, :update, :show, :destory]
  before_action :require_user,except: [:index,:show]
  before_action :require_same_user,only: [:edit,:destroy,:update]
  def index
    @recipes=Recipe.paginate(page: params[:page],per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe=Recipe.new(recipe_params)
    @recipe.chef=current_chef
    if @recipe.save
        flash[:notice]="Recipe was created Successfully"
        redirect_to  recipe_path(@recipe)
    else
        render 'new'
    end
  end

  def show
    @comments=@recipe.comments.paginate(page: params[:page],per_page: 5)
  end

  def destroy
    @recipe.destroy
     redirect_to '/recipes',status: :see_other
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:notice]="Recipe was Updated Successfully"
      redirect_to  recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  private

  def recipe_params
      params.require(:recipe).permit(:name,:description,ingredient_ids: [])
  end

  def set_recipe
    @recipe=Recipe.find(params[:id])
  end

  def require_same_user
    if current_chef!=@recipe.chef and !current_chef.admin?
      flash[:danger]="You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end
  def create
    chef=Chef.find_by(email: params[:session][:email].downcase)
    if chef && chef.authenticate(params[:session][:password])
      session[:chef_id]=chef.id
      flash[:success]="You have successfully logged in"
      redirect_to chef_path(chef)
    else
      flash.now[:danger]="There was something wrong with your login info"
      render 'new'
    end
  end
  def destroy
    session[:chef_id]=nil
    flash[:success]="You have logged out"
    redirect_to root_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(user,options={})
    gravatar_id=Digest::MD5::hexdigest(user.email.downcase)
    size=options[:size||80]
    gravatar_url="https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url,alt: user.name,class: "img-circle")
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/chefs_helper.rb
module ChefsHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_footer.html.erb
<!--footer-->
<footer class="footer1">
<div class="container">

<div class="row"><!-- row -->

                <div class="col-lg-3 col-md-3"><!-- widgets column left -->
                <ul class="list-unstyled clear-margins"><!-- widgets -->

                        	<li class="widget-container widget_nav_menu"><!-- widgets list -->

                                <h1 class="title-widget">Useful links</h1>

                                <ul>
                                	<li><a  href="#"><i class="fa fa-angle-double-right"></i> About Us</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i> Contact Us</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i> Success Stories</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i> PG Courses</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i> Achiever's Batch</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Regular Batch</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Test & Discussion</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Fast Track T & D</a></li>
                                </ul>

							</li>

                        </ul>


                </div><!-- widgets column left end -->



                <div class="col-lg-3 col-md-3"><!-- widgets column left -->

                <ul class="list-unstyled clear-margins"><!-- widgets -->

                        	<li class="widget-container widget_nav_menu"><!-- widgets list -->

                                <h1 class="title-widget">Useful links</h1>

                                <ul>
 									<li><a  href="#"><i class="fa fa-angle-double-right"></i>  Test Series Schedule</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Postal Coaching</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  PG Dr. Bhatia Books</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  UG Courses</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Satellite Education</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  Study Centres</a></li>
                                    <li><a  href="#"><i class="fa fa-angle-double-right"></i>  State P.G. Mocks</a></li>
                                    <li><a  href="#" target="_blank"><i class="fa fa-angle-double-right"></i> Results</a></li>

                                </ul>

							</li>

                        </ul>


                </div><!-- widgets column left end -->



                <div class="col-lg-3 col-md-3"><!-- widgets column left -->

                <ul class="list-unstyled clear-margins"><!-- widgets -->

                        	<li class="widget-container widget_nav_menu"><!-- widgets list -->

                                <h1 class="title-widget">Useful links</h1>

                                <ul>


                <li><a href="#"><i class="fa fa-angle-double-right"></i> Enquiry Form</a></li>
 				<li><a href="#"><i class="fa fa-angle-double-right"></i> Online Test Series</a></li>
				<li><a href="#"><i class="fa fa-angle-double-right"></i> Grand Tests Series</a></li>
				<li><a href="#"><i class="fa fa-angle-double-right"></i> Subject Wise Test Series</a></li>
				<li><a href="#"><i class="fa fa-angle-double-right"></i> Smart Book</a></li>
				<li><a href="#"><i class="fa fa-angle-double-right"></i> Test Centres</a></li>
                <li><a href="#"><i class="fa fa-angle-double-right"></i>  Admission Form</a></li>
				<li><a href="#"><i class="fa fa-angle-double-right"></i>  Computer Live Test</a></li>

                                </ul>

							</li>

                        </ul>


                </div><!-- widgets column left end -->


                <div class="col-lg-3 col-md-3"><!-- widgets column center -->



                        <ul class="list-unstyled clear-margins"><!-- widgets -->

                        	<li class="widget-container widget_recent_news"><!-- widgets list -->

                                <h1 class="title-widget">Contact Detail </h1>

                                <div class="footerp">

                                <h2 class="title-median">Webenlance Pvt. Ltd.</h2>
                                <p><b>Email id:</b> <a href="mailto:info@webenlance.com">info@webenlance.com</a></p>
                                <p><b>Helpline Numbers </b>

    <b style="color:#ffc106;">(8AM to 10PM):</b>  +91-8130890090, +91-8130190010  </p>

    <p><b>Corp Office / Postal Address</b></p>
    <p><b>Phone Numbers : </b>7042827160, </p>
    <p> 011-27568832, 9868387223</p>
                                </div>

                                <div class="social-icons">

                                	<ul class="nomargin">

                <a href="https://www.facebook.com/bootsnipp"><i class="fa fa-facebook-square fa-3x social-fb" id="social"></i></a>
	            <a href="https://twitter.com/bootsnipp"><i class="fa fa-twitter-square fa-3x social-tw" id="social"></i></a>
	            <a href="https://plus.google.com/+Bootsnipp-page"><i class="fa fa-google-plus-square fa-3x social-gp" id="social"></i></a>
	            <a href="mailto:bootsnipp@gmail.com"><i class="fa fa-envelope-square fa-3x social-em" id="social"></i></a>

                                    </ul>
                                </div>
                    		</li>
                          </ul>
                       </div>
                </div>
</div>
</footer>
<!--header-->

<div class="footer-bottom">

	<div class="container">

		<div class="row">

			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

				<div class="copyright">

					© 2015, Webenlance, All rights reserved

				</div>

			</div>

			<div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">

				<div class="design">

					 <a href="#">Franchisee </a> |  <a target="_blank" href="http://www.webenlance.com">Web Design & Development by Webenlance</a>

				</div>

			</div>

		</div>

	</div>

</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "My Recipies" ,root_path,class: "navbar-brand",id:"logo"%>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Chefs",chefs_path%></li>
        <li class="navLink"><%= link_to "All Recipes" ,recipes_path %></li>
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle navLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Recipes <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "Create new recipe", new_recipe_path%></li>
              <li><a href="#">Another action</a></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Separated link</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Another Link to work with</a></li>
            </ul>
          </li>
        <% end %>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle navLink" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Ingredients <span class="caret"></span></a>
         <ul class="dropdown-menu">
              <li><%= link_to "All Ingredient", ingredients_path%></li>
              <% Ingredient.all.each do |ingredient| %>
                <li><%= link_to ingredient.name.capitalize,ingredient_path(ingredient)%></li>
              <% end %>
              <% if logged_in? && current_chef.admin? %>
              <li role="separator" class="divider"></li>
              <li><%= link_to "New Ingredient", new_ingredient_path %></li>
              <% end %>
            </ul>
          </li>
        </ul>
        </li>
      <form class="navbar-form navbar-left">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle navLink"  data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_chef.name.capitalize%>'s profile <%= "Admin" if current_chef.admin?%> <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%=link_to "View your profile", chef_path(current_chef) %></li>
              <li><%=link_to "Edit your profile", edit_chef_path(current_chef) %></li>
              <li><a href="#">Something else here</a></li>
              <li role="separator" class="divider"></li>
              <li><%= button_to "Logout",logout_path,method: :delete,data:{turbo_confirm: "Are you sure to logout"} %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in",login_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myrecipies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag :application %>
  </head>

  <body>
    <%= render "layouts/navigation"%>
    <div class="container">
    <%= yield %>
    </div>
    <%= render "layouts/footer"%>
  </body>
</html>

app/views/pages/home.html.erb
<div class="jumbotron center">
    <h1>Welcome to MyRecipes</h1>
    <h2>The best recipe sharing app!</h2>
    <p><%= link_to "View All Recipes", recipes_path, class:"btn btn-danger btn-lg btn-xlarge" %></p>
</div>
<div class="row">
    <div class="col-lg-4">
        <h2>Safari bug warning!</h2>
        <p class="text-danger">As of v9.1.2, Safari exhibits a bug in which resizing your browser horizontally causes rendering errors in the justified nav that are cleared upon refreshing.</p>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
    </div>
    <div class="col-lg-4">
        <h2 >Heading</h2>
        <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
    </div>
    <div class="col-lg-4">
        <h2>Heading</h2>
        <p>Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa.</p>
        <p><a class="btn btn-primary btn-xlarge" href="#" role="button">View details »</a></p>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
        <div class="col-md-8 col-md-offset-2" >
            <div class="panel panel-danger">
                <div class="panel-heading">
                    <h2 class="panel-title">
                    <%= pluralize(obj.errors.count,"error") %>
                        prohibited this <%= obj.class %> from being saved:
                    </h2>
                    <div class="panel-body">
                        <ul>
                            <% obj.errors.full_messages.each do |msg| %>
                            <li> <%= msg %> </li>
                            <% end %>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
<% end %>

app/views/shared/_page_title.html.erb
<h1 align="center" ><%= title.capitalize %></h1>
<hr />